name: electricity
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - tensorflow
  - ipykernel
  - statsmodels
  - jupyterlab
  - matplotlib
  - seaborn
  - pip
  - pip:
      - optuna
      - arch
